name: Tests
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Assemble release
        run: ./gradlew assembleRelease

      - name: Run checks
        if: success() || failure()
        run: ./gradlew check

      - name: Run Detekt
        if: success() || failure()
        run: ./gradlew detekt

      - name: Run Lint
        if: success() || failure()
        run: ./gradlew lint

      - name: Upload Detekt results
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/detekt-report.sarif
          category: detekt

      - name: Upload Lint results
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: app/build/reports/lint-results-debug.sarif
          category: lint